---
version: "3.2"
services:
  builder:
    build:
      context: .
    volumes:
      - type: volume
        source: site
        target: /usr/local/tomcat/target
    ports:
      - "8080:8080"


volumes:
  site: